/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MehForm {
        /**
          * The base URL for where the meh system is hosted If not provided, defaults to same origin
         */
        "backend": string;
        /**
          * Custom translations object that overrides default and loaded translations This allows users to provide their own translations directly
         */
        "customTranslations": string | Partial<typeof this.defaultTranslations>;
        /**
          * The language code for translations If not provided, defaults to 'en'
         */
        "language": string;
        /**
          * The post path to associate the comment with If not provided, defaults to the current page path
         */
        "post": string;
    }
}
declare global {
    interface HTMLMehFormElement extends Components.MehForm, HTMLStencilElement {
    }
    var HTMLMehFormElement: {
        prototype: HTMLMehFormElement;
        new (): HTMLMehFormElement;
    };
    interface HTMLElementTagNameMap {
        "meh-form": HTMLMehFormElement;
    }
}
declare namespace LocalJSX {
    interface MehForm {
        /**
          * The base URL for where the meh system is hosted If not provided, defaults to same origin
         */
        "backend"?: string;
        /**
          * Custom translations object that overrides default and loaded translations This allows users to provide their own translations directly
         */
        "customTranslations"?: string | Partial<typeof this.defaultTranslations>;
        /**
          * The language code for translations If not provided, defaults to 'en'
         */
        "language"?: string;
        /**
          * The post path to associate the comment with If not provided, defaults to the current page path
         */
        "post"?: string;
    }
    interface IntrinsicElements {
        "meh-form": MehForm;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "meh-form": LocalJSX.MehForm & JSXBase.HTMLAttributes<HTMLMehFormElement>;
        }
    }
}
