name: Build Release Archive

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Install Composer dependencies
        run: |
          cd backend
          composer install --no-interaction --no-progress --no-suggest --no-dev --optimize-autoloader

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Build Frontend
        run: |
          cd frontend
          npm ci
          npm run build

      - name: Create release directory
        run: |
          mkdir -p release
          
      - name: Copy backend files
        run: |
          cp -r backend/* release/
          # Remove development files
          rm -f release/composer.lock
          rm -rf release/tests
          
      - name: Copy public directory and frontend build
        run: |
          cp -r public release/
          cp -r frontend/dist/* release/public/meh/
          
      - name: Copy additional files
        run: |
          cp README.md release/
          cp LICENSE release/
          
      - name: Create zip archive
        run: |
          cd release
          zip -r ../meh-release.zip .
          cd ..
          
      - name: Get version from tag
        id: version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "version=dev-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          fi
          
      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: meh-release-${{ steps.version.outputs.version }}
          path: meh-release.zip
          retention-days: 90
          
      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: meh-release.zip
          name: Release ${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
